name: linting and testing  
on: [push]  
jobs:  
  pipeline:  
    runs-on: ubuntu-latest  
    strategy:  
      matrix:  
        node-version: [ 20.x ]  
  
    steps:  
      - uses: actions/checkout@v2  
      - name: Staring Node.js ${{ matrix.node-version }}  
        uses: actions/setup-node@v1  
        with:  
          node-version: ${{ matrix.node-version }}  
      - name: install modules  
        run: npm install --force
        if: always()
      - name: linting typescript  
        run: npm run lint:fix
        if: always()  
      - name: unit testing  
        run: npm run test
        if: always()